## This dockerfile is for setting nexus services

## version: v0.1

## date: 2025-03-04



# Nexus3 공식 이미지 기반

FROM sonatype/nexus3:latest



# 루트 사용자 변경

USER root



# 필수 패키지 설치 (jq, Restic, GPG 키, curl)

RUN microdnf install -y gnupg2 unzip bzip2

RUN microdnf install -y jq 

RUN microdnf clean all



# AWS CLI 직접 다운로드 및 설치

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \

    unzip awscliv2.zip && \

    ./aws/install && \

    rm -rf awscliv2.zip aws



# Restic 직접 다운로드 및 설치

RUN ARCH=$(uname -m) && \

    if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi && \

    if [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi && \

    RESTIC_VERSION="0.17.3" && \

    curl -sSL "https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_linux_${ARCH}.bz2" -o "/usr/local/bin/restic.bz2" && \

    bzip2 -d /usr/local/bin/restic.bz2 && \

    chmod +x /usr/local/bin/restic



# Nexus 실행

CMD ["/opt/sonatype/nexus/bin/nexus", "run"]

